name: MCProtocolLib Build

on:
    pull_request:
    push:
        branches:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Gradle Wrapper Verification
              uses: gradle/wrapper-validation-action@v3

            - name: Setup JDK
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Elevate wrapper permissions
              run: chmod +x ./gradlew

            - name: Build
              uses: gradle/gradle-build-action@v3
              with:
                  arguments: build

