name: MCProtocolLib 1.21.10 Publish

on:
    workflow_dispatch:
    push:
        branches:
            - "1.21.10"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v6

            - name: Setup JDK
              uses: actions/setup-java@v5
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Elevate wrapper permissions
              run: chmod +x ./gradlew

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v5

            - name: Publish
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
                  PUBLISH_VERSION: "1.21.10.${{ github.run_number }}"
              run: ./gradlew build publishMavenPublicationToVcRepository
