name: MCProtocolLib 1.20.4 Publish

on:
    push:
        branches:
            - "1.20.4"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Gradle Wrapper Verification
              uses: gradle/wrapper-validation-action@v3

            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Elevate wrapper permissions
              run: chmod +x ./gradlew

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            - name: Publish
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
                  PUBLISH_VERSION: "1.20.4.${{ github.run_number }}"
              run: ./gradlew build publishMavenPublicationToVcRepository
